img_size: [120,160]
top_cutoff: 40
#top_cutoff: 30
#top_cutoff: 35

detector: 
  - line_detector.LineDetectorHSV
  - configuration:
      dilation_kernel_size: 3
      canny_thresholds: [60,150]
      hough_threshold: 20 # 20
      hough_min_line_length: 10 # 10
      hough_max_line_gap:    30 # 30
      parking: 0


      hsv_white1:  [0,0,150]
      hsv_white2:  [180,50,255]
      hsv_yellow1:  [10,70,100]
      hsv_yellow2:  [75,255,250]
#      hsv_yellow1: [10,70,100] #[25,70,100]#[25,100,120]#[25,50,90]
#      hsv_yellow2: [55,255,255] #[45,255,255]
      hsv_red1:    [0,200,200]
      hsv_red2:    [15,255,255]
      hsv_red3:    [165,200,200]
      hsv_red4:    [180,255,255]

detector2:
  - line_detector.LineDetector2Dense
  - configuration:
        dilation_kernel_size: 3
        canny_thresholds: [80,200]
        sobel_threshold: 40.

        hsv_white1:  [0,0,150]
        hsv_white2:  [180,60,255]
        hsv_yellow1: [10,70,100]
        hsv_yellow2: [75,255,250]
        hsv_red1:    [0,200,200]
        hsv_red2:    [15,255,255]
        hsv_red3:    [165,200,200]
        hsv_red4:    [180,255,255]

#hsv_yellow1: [25,10,90]

#      hsv_white1:  [0,0,150]
#      hsv_white2:  [180,100,255]
#      hsv_yellow1: [25,50,50]
#      hsv_yellow2: [45,255,255]
#      hsv_red1:    [0,100,100]
#      hsv_red2:    [15,255,255]
#      hsv_red3:    [165,100,100]
#      hsv_red4:    [180,255,255]
